### PR TITLE
Update to use ghost 2.0

### PR DESCRIPTION
**Pull request by marksyzm**
I updated it so all the errors except for the CSS ones are fixed when implementing this into ghost 2. Not sure why the errors are there as I have included the necessary changes in `_global.scss`.

Also you might want to publish this separately to npm (if you choose to do so) as it may break usage in 1.0? I think they've left the aliases in place so this doesn't happen but it's worth checking through.

### CODE REVIEW

**Comment by jamesfacts** [comment]
Thanks so much for doing all the legwork, I've been meaning to get this theme updated to Ghost 2.0. I notice that this webpack config no longer builds successfully—did you get it running? I'll merge your PR and update the dependencies in a moment.

**Comment by marksyzm** [comment]
I actually did that too but it's not in here. It wasn't too much bother; just needed to update the Babel core stuff. You need @babel/core along with @babel/env and update the Babel config file, plus alter Babel clean so it passes in an object. I'll have a go this morning.

**Comment by jamesfacts** [comment]
I actually did update webpack last night—I was just curious if you had tested it locally a different way. Here's [the commit where I revised the webpack stuff](https://github.com/jamesfacts/frontier-ghost-theme/commit/f37b51ede9d79de3ca1a07b9ed3656ba408529d6). I didn't touch Babel or `extract-text-webpack-plugin` if you wanna take a look at those!

**Comment by marksyzm** [comment]
I just noticed that the get API isn't working and that this needs to be added to the engines property in package.json also:
```
  "engines": {
    "ghost-api": "v2"
  },
```

**Comment by jamesfacts** [comment]
Good catch! I made [that change](https://github.com/jamesfacts/frontier-ghost-theme/commit/cbd4ce4d4c02b43a48b1611815cbc52a09a8078e) just now

**Comment by marksyzm** [comment]
Might be worth checking the package.json on the Casper template for any other oddities

**Pull request merged**
